name: Install and Call Python Script

on: 
  push: 
  workflow_dispatch: 
  

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: 1
        run: echo "Hello Dresden!"
      - name: 2
        run: echo "Pon4ik privet"
